window.trackerDefaults = {
  '10 Bronze Wizard Cards without getting a health increase': 'counter',
  '20 Bronze Wizard Cards': 'counter',
  '30 Bronze Wizard Cards': 'counter',
  '23 Wizard Cards': 'counter',
  '37 Wizard Cards': 'counter',
  '53 Wizard Cards': 'counter',
  '8 different Rictusempra Challenge Stars': 'counter',
  '8 different Skurge Challenge Stars': 'counter',
  '8 different Spongify Challenge Stars': 'counter',
  '9 different Diffindo Challenge Stars': 'counter',
  '13 different Diffindo Challenge Stars': 'counter',
  '8 different Skurge Challenge Stars': 'counter',
  '8 different Gryffindor Challenge Stars': 'counter',
  '4 Spell Challenge completion stars': 'tokens',
  '17 different Challenge Stars': 'counter',
  '31 different Challenge Stars': 'counter',
  '4 Challenge Completion Stars': 'tokens',
  '5 different Challenge Stars from each challenge': 'tokens',
  'Open 4 Peeves chests': 'tokens',
  '8 Unique Flobberworm Mucus': 'counter',
  '6 Wizard Cards in Goyle': 'counter',
  '6 Wizard Cards in Skurge': 'counter',
  '8 Wizard Cards in Diffindo': 'counter',
  'Buy 3 Silver Wizard Cards': 'counter',
  'Buy 4 Bronze Wizard Cards': 'counter',
  'Buy 8 Wizard Cards': 'counter',
  'Cast at 3 different Lumos statues in Willow': 'counter',
  'Cast at 8 different Lumos statues in Goyle': 'counter',
  'Cast at 5 different Lumos statues in Spongify': 'counter',
  'Cast at 2 different Lumos statues in the GWC Challenge': 'counter',
  'Clip 7 Gnomes out of bounds': 'counter',
  'Kill 10 bowtruckles': 'counter',
  'Kill 12 spiders outside the Aragog fight': 'counter',
  'Kill 7 Imps': 'counter',
  'Empty 8 flower pots': 'counter',
  'Empty 10 armor stands': 'counter',
  'Empty 7 bean boxes': 'counter',
  'Empty 10 cauldrons': 'counter'
};
